name: CI-Build

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Docker Registry      
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - 
        name: Building Docker Image
        env:
          CONTAINER_IMAGE_NAME: "avaxxx/aspnetcore-docker-demo:arm-15"
        run:
           docker build -t $CONTAINER_IMAGE_NAME .	          
      - 
        name: Push Docker Container to Registry
        env:
          CONTAINER_IMAGE_NAME: "avaxxx/aspnetcore-docker-demo:arm-15"   
        run: docker push $CONTAINER_IMAGE_NAME
        # name: Docker
        # uses: jerray/publish-docker-action@master
        # with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}
        #   repository: avaxxx/aspnetcore-docker-demo
        #   auto_tag: "true"