name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 . --tag my-image-name:$(date +%s)
