name: CI-Build

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      - name: Building Docker Image
        env:
          CONTAINER_IMAGE_NAME: "avaxxx/aspnetcore-docker-demo:arm-15"
        run:
           docker build -t $CONTAINER_IMAGE_NAME --file ./Dockerfile-web .
      - name: Push Docker Container to Registry
        env:
          CONTAINER_IMAGE_NAME: "avaxxx/aspnetcore-docker-demo:arm-15"
        run: docker push $CONTAINER_IMAGE_NAME